package pro.sky.animal_shelter.chatStates;

public enum ChatStateForContactInfo {
    DROP,
    NONE,
    WAITING_FOR_CONFIRMATION,
    WAITING_FOR_DIET_OF_PET,
    WAITING_FOR_FULL_NAME,
    WAITING_FOR_HABITSCHANGES_INFO,
    WAITING_FOR_PHONE_NUMBER,
    WAITING_FOR_WELLBEING_INFO,
    WAITING_FOR_TELEGRAM_ID_OF_NEW_PET_OWNER,
    WAITING_FOR_TELEGRAM_ID_OF_REJECTED_PET_OWNER
}
