package pro.sky.animal_shelter.chatStates;

public enum ChatStateForContactInfo {
    NONE,
    WAITING_FOR_CONFIRMATION,
    WAITING_FOR_FULL_NAME,
    WAITING_FOR_PHONE_NUMBER,
    DROP,
    DEFAULT,
    WAITING_FOR_PHOTO_OF_PET,
    WAITING_FOR_DIET_OF_PET,
    WAITING_FOR_WELLBEING_INFO,
    WAITING_FOR_HABITSCHANGES_INFO
}
